version: '3.7'

services:
  vue_app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: my_vue_app_container
      ports:
        - "80:80"
      networks:
        - my_network

networks:
  my_network:
    driver: bridge